server:
  port: 8004

spring:
  application:
    name: wink-springcloud-payment
  cloud:
    consul:
      host: 192.168.124.7
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: payment8004
        health-check-critical-timeout: 5s
        health-check-interval: 10s


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.7:3306/?useUnicode=true&charcterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: pyq7588479