server:
  port: 8001

spring:
  application:
    name: wink-springcloud-payment

#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.124.7:3306/?useUnicode=true&charcterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#    username: root
#    password: pyq7588479